name: gps_trace
author: gerald reinhart
description: Parsing and analysing gps trace files
homepage: https://github.com/GeReinhart/dart-gps-trace
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  petitparser: 1.0.0
  unittest: any
